- name: Waiting for nodes to be reachable
  wait_for_connection:
    sleep: 10
    timeout: 600

- name: Gather System Info
  setup:

- name: Gather Installed Services
  service_facts:

- name: Add mappings to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.hostname }} {{ item.name }}"
    state: present
  with_items: "{{ etc_host_entries }}"
