# We need updated ca-certificates to add OpenFlight Repo.  Let's just updated
# every package.
- name: Update packages
  yum: name=ca-certificates state=latest

- name: Install EPEL Repo
  yum: name=epel-release state=present

- name: Add OpenFlight Release Repo
  yum: 
    name: "https://repo.openflighthpc.org/openflight/centos/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/openflighthpc-release-3-1.noarch.rpm"
    state: present
    disable_gpg_check: yes

- name: Enabling OpenFlight Development Repo
  ini_file:
    dest: /etc/yum.repos.d/openflight.repo
    section: openflight-dev
    option: enabled
    value: 1
  when: enable_dev_repos

- name: Enable PowerTools repository
  ini_file:
    dest: /etc/yum.repos.d/CentOS-PowerTools.repo
    section: PowerTools
    option: enabled
    value: 1
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8'
