# Miscellaneous fixes to adjust the cluster to better support being ran as a
# vagrant machine.

# Vagrant cannot forward guest ports to privileged ports on the host.  To
# support redirecting from HTTP to HTTPS correctly, we configure `flight-www`
# to run on the same ports as we forward on the host.
- name: Change ports for Flight WWW
  shell: |
    /opt/flight/bin/flight service configure www --config '{"port": "8080", "https_port": "8443"}'
  when:
    - slurm_role == 'controller'
    # Production `flight-service` currently doesn't support `--config`.
    - flavour != 'production'

- name: Manually change ports for Flight WWW
  shell: |
    echo <<EOF
    You need to manually configure the ports for Flight WWW.
    Run the following and set HTTP Port to 8080 and HTTPS Port to 8443

      /opt/flight/bin/flight service configure www

    EOF
  when:
    - slurm_role == 'controller'
    # Production `flight-service` currently doesn't support `--config`.
    - flavour == 'production'

- name: Restart Flight WWW
  command: /opt/flight/bin/flight service restart www
  when: slurm_role == 'controller'
