---
- name: Configure HPC Environment for OpenFlightHPC Compute
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  gather_facts: False
  roles:
    - base
    - upstream
    - slurm
    # The NFS role/tasks changes the `.ssh/authorized_keys` file on the
    # compute nodes, breaking ansible access to them. So `nfs` must be ran
    # after ansible has finished with the compute nodes.
    - nfs
    - flightenv
    - flightenv-bootstrap
    - flightweb
    - vagrant-fixes
    - dev-setup
