---
- name: Configure HPC Environment for OpenFlightHPC Compute
  hosts: all
  # remote_user: root
  # sudo: yes
  become: true
  become_user: root
  become_method: sudo
  gather_facts: False
  roles:
    - upstream
    - slurm
    - nfs
    - flightenv
    - flightenv-bootstrap
    - flightweb
